# Generated by Django 3.0.5 on 2020-11-24 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('university', models.TextField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('facebookURL', models.URLField(blank=True, null=True)),
                ('instagramURL', models.URLField(blank=True, null=True)),
                ('linkedinURL', models.URLField(blank=True, null=True)),
                ('twitterURL', models.URLField(blank=True, null=True)),
                ('current_position', models.TextField(default='Volunteer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
