Requirement already up-to-date: google-api-python-client in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (1.9.1)
Requirement already up-to-date: google-auth-httplib2 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (0.0.3)
Requirement already up-to-date: google-auth-oauthlib in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (0.4.1)
Requirement already satisfied, skipping upgrade: google-auth>=1.16.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-python-client) (1.16.1)
Requirement already satisfied, skipping upgrade: six<2dev,>=1.6.1 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-python-client) (1.14.0)
Requirement already satisfied, skipping upgrade: google-api-core<2dev,>=1.17.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-python-client) (1.19.0)
Requirement already satisfied, skipping upgrade: uritemplate<4dev,>=3.0.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-python-client) (3.0.1)
Requirement already satisfied, skipping upgrade: httplib2<1dev,>=0.9.2 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-python-client) (0.18.1)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=0.7.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-auth-oauthlib) (1.3.0)
Requirement already satisfied, skipping upgrade: rsa<4.1,>=3.1.4 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-auth>=1.16.0->google-api-python-client) (4.0)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-auth>=1.16.0->google-api-python-client) (4.1.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-auth>=1.16.0->google-api-python-client) (0.2.8)
Requirement already satisfied, skipping upgrade: setuptools>=40.3.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-auth>=1.16.0->google-api-python-client) (41.2.0)
Requirement already satisfied, skipping upgrade: pytz in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-core<2dev,>=1.17.0->google-api-python-client) (2020.1)
Requirement already satisfied, skipping upgrade: requests<3.0.0dev,>=2.18.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-core<2dev,>=1.17.0->google-api-python-client) (2.23.0)
Requirement already satisfied, skipping upgrade: googleapis-common-protos<2.0dev,>=1.6.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-core<2dev,>=1.17.0->google-api-python-client) (1.52.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.4.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from google-api-core<2dev,>=1.17.0->google-api-python-client) (3.12.2)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.1.0)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from rsa<4.1,>=3.1.4->google-auth>=1.16.0->google-api-python-client) (0.4.8)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.17.0->google-api-python-client) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.17.0->google-api-python-client) (1.25.9)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.17.0->google-api-python-client) (2.9)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\iulia\documents\liicenta\liicenta\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<2dev,>=1.17.0->google-api-python-client) (2020.4.5.1)
